package org.mindera.model.hotel;

public enum Facilities {
    FITNESSCENTER,
    RESTAURANT,
    SPA,
    INTERIORSWIMMINGPOOL,
    EXTERIORSWIMMINGPOOL,
    BAR,
    PARKING,
    ROOMSERVICE,
    PETSALLOWED,
    AIRTPORTSHUTTLE,
    ELECTRICCARCHARGINGSTATION;


}
